name: 'Set up a Doom Emacs environment'
description: 'Install a specific version of Doom Emacs (and Emacs) for use in your workflow.'
author: 'Henrik Lissner'

inputs:
  version:
    description: 'The version, branch, tag, or SHA of Doom core to install, e.g. "v3.0.0", or "master" for the latest development version.'
    type: string
    default: ""
  emacs-version:
    description: 'The version of Emacs to install, e.g. "28.1", or "snapshot" for a recent development version.'
    type: string
    default: "28.1"
  emacsdir:
    description: "TODO"
    type: string
    default: ".emacs.d"
  doomdir:
    description: "TODO"
    type: string
    default: ".doom.d"
  sync:
    description: "Whether or not to automatically run 'doom sync'"
    type: boolean
    default: true
  sync-options:
    description: "Options to pass to initial 'doom sync'"
    type: string
    default: ""

runs:
  using: 'composite'
  env:
    EMACSDIR: ${{ inputs.emacsdir }}
    DOOMDIR:  ${{ inputs.doomdir }}
  steps:
    - uses: purcell/setup-emacs@master
      if: runner.os != 'Windows'
      with.version: ${{ inputs.emacs-version }}

    - uses: actions/setup-python@v2
      if: runner.os == 'Windows'
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: jcs090218/setup-emacs-windows@master
      if: runner.os == 'Windows'
      with.version: ${{ inputs.emacs-version }}

    - name: Checkout Doom Emacs
      uses: actions/checkout@v3.0.2
      with:
        repository: doomemacs/doomemacs
        path: ${{ inputs.emacsdir }}
        ref: ${{ inputs.version }}

    - name: Add bin/doom to PATH
      shell: bash
      run: |
        perl -MCwd -le 'print Cwd::abs_path shift' ${{ inputs.emacsdir }} >> $GITHUB_PATH

    - name: Cache packages
      uses: actions/cache@v3
      env.hash: |
        ${{ hashFiles(
              format('{0}/**/packages.el', inputs.emacsdir),
              format('{0}/**/packages.el', inputs.doomdir),
              format('{0}/init.el', inputs.doomdir)) }}
      with:
        path: ${{ inputs.emacsdir }}/.local/straight/repos
        key: build-${{ runner.os }}-${{ inputs.emacs-version }}-${{ env.hash }}
        restore-keys: |
          build-${{ runner.os }}-${{ inputs.emacs-version }}-
          build-${{ runner.os }}--
          build---

    - name: doom sync
      if: inputs.sync
      run: doom ${{ inputs.sync-options }} sync
