name: Run tests
on:
  workflow_call:
    inputs:
      testdir:
        description: "TODO"
        type: string
        default: "test"
      config-file:
        description: "TODO"
        type: string
        default: '.github/ci.el'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs_version: [27.1, 27.2, 28.1, snapshot]
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: doomemacs/ci@main
        with.emacs-version: ${{ matrix.emacs_version }}
      - name: Run tests
        run: .emacs.d/bin/doom -f ${{ inputs.config-file }} ci run-tests ${{ inputs.testdir }}
      # - name: Compile
      #   run: "bin/doom -y compile"
