name: Add issues to project
on:
  workflow_call:
    inputs:
      project-url:
        description: "TODO"
        type: string
        default: https://github.com/orgs/doomemacs/projects/2
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: ${{ inputs.project-url }}
          github-token: ${{ github.token }}
          labeled: needs-triage
