name: Lint commits
on: [workflow_call]
jobs:
  lint-commits:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with.access_token: ${{ github.token }}

      - name: Set up Doom Emacs CI
        uses: doomemacs/ci@legacy

      - uses: actions/checkout@v3.0.2
        with.fetch-depth: 0

      - name: Run commit linter
        env:
          FROM: ${{ github.event.pull_request.base.sha }}
          TO:   ${{ github.event.pull_request.head.sha }}
        run: doom ci lint-commits $FROM $TO
