name: Lint commits
on:
  workflow_call:
    secrets:
      token:
        description: 'Token for repository access'
        required: false
        default: ${{ github.token }}
    inputs:
      config-file:
        description: "TODO"
        type: string
        default: '.github/ci.el'

jobs:
  lint-commits:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with.access_token: ${{ secrets.token }}

      - name: Set up Doom Emacs CI
        uses: doomemacs/ci@legacy

      - name: Checkout current project
        uses: actions/checkout@v3.0.2
        with.fetch-depth: 0

      - name: Run commit linter
        env.ELFILE: ${{ inputs.config-file }}
        run: |
          [[ -f "$ELFILE" ]] || ELFILE=
          doom ${ELFILE:+-l "$ELFILE"} ci lint-commits ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
