name: Run tests
on:
  workflow_call:
    inputs:
      testdir:
        description: "TODO"
        type: string
        default: "test/"
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [27.1, 27.2, 28.1, snapshot]
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: doomemacs/ci@main
        with.emacs-version: ${{ matrix.emacs-version }}

      - run: doom ci run-tests ${{ inputs.testdir }}
